### ISSUE TITLE
crash when teleporting to friend 

### ISSUE THREAD

**Issue by mgracer48** [InvisbleMario/CIOIssueTracker#14]
KeyError: None
Traceback (most recent call last):
  File "__main__", line 12, in <module>
  File "lib.coginvasion.base.CIStartGlobal", line 11, in <module>
  File "lib.coginvasion.base.CIStart", line 142, in <module>
  File "direct.showbase.ShowBaseWide", line 2982, in run
  File "direct.task.Task", line 508, in run
  File "direct.task.Task", line 465, in step
  File "direct.distributed.ConnectionRepository", line 613, in readerPollUntilEmpty
  File "direct.distributed.ConnectionRepository", line 620, in readerPollOnce
  File "lib.coginvasion.distributed.CogInvasionClientRepository", line 799, in handleDatagram
  File "lib.coginvasion.distributed.CogInvasionClientRepository", line 805, in astronHandle
  File "direct.distributed.AstronClientRepository", line 64, in handleDatagram
  File "direct.distributed.DoInterestManager", line 618, in handleInterestDoneMessage
  File "direct.showbase.Messenger", line 326, in send
  File "direct.showbase.Messenger", line 411, in __dispatch
  File "lib.coginvasion.distributed.CogInvasionClientRepository", line 211, in _handleEmuSetZoneDone
  File "direct.showbase.Messenger", line 326, in send
  File "direct.showbase.Messenger", line 411, in __dispatch
  File "lib.coginvasion.hood.QuietZoneState", line 96, in _handleQuietZoneResponse
  File "direct.showbase.Messenger", line 326, in send
  File "direct.showbase.Messenger", line 411, in __dispatch
  File "lib.coginvasion.distributed.PlayGame", line 239, in handleEnteredQuietZone
KeyError: None

**Comment by mgracer48** [comment]
this is fixed appearntly
