### ISSUE TITLE
crash with placing turret

### ISSUE THREAD

**Issue by mgracer48** [InvisbleMario/CIOIssueTracker#19]
Traceback (most recent call last):
  File "__main__", line 12, in <module>
  File "lib.coginvasion.base.CIStartGlobal", line 11, in <module>
  File "lib.coginvasion.base.CIStart", line 142, in <module>
  File "direct.showbase.ShowBaseWide", line 2982, in run
  File "direct.task.Task", line 508, in run
  File "direct.task.Task", line 465, in step
  File "direct.distributed.ConnectionRepository", line 613, in readerPollUntilEmpty
  File "direct.distributed.ConnectionRepository", line 620, in readerPollOnce
  File "lib.coginvasion.distributed.CogInvasionClientRepository", line 799, in handleDatagram
  File "lib.coginvasion.distributed.CogInvasionClientRepository", line 805, in astronHandle
  File "direct.distributed.AstronClientRepository", line 64, in handleDatagram
  File "direct.distributed.ClientRepositoryBase", line 438, in handleUpdateField
  File "direct.distributed.ClientRepositoryBase", line 446, in __doUpdate
  File "lib.coginvasion.battle.DistributedPieTurretManager", line 57, in turretPlaced
AttributeError: 'NoneType' object has no attribute 'b_setGag'

**Comment by xMakerx** [comment]
This bug has been corrected in v1.0.3.
