### ISSUE TITLE
Crash caused by cannon?

### ISSUE THREAD

**Issue by InvisbleMario** [InvisbleMario/CIOIssueTracker#3]
The turret button appeared in the bottom right when I started so I went to where I wanted to place it and I hit it. :tada: :boom: :tada: 

Log:

Traceback (most recent call last):
  File "__main__", line 12, in <module>
  File "lib.coginvasion.base.CIStartGlobal", line 11, in <module>
  File "lib.coginvasion.base.CIStart", line 142, in <module>
  File "direct.showbase.ShowBaseWide", line 2982, in run
  File "direct.task.Task", line 508, in run
  File "direct.task.Task", line 465, in step
  File "direct.distributed.ConnectionRepository", line 613, in readerPollUntilEmpty
  File "direct.distributed.ConnectionRepository", line 620, in readerPollOnce
  File "lib.coginvasion.distributed.CogInvasionClientRepository", line 799, in handleDatagram
  File "lib.coginvasion.distributed.CogInvasionClientRepository", line 805, in astronHandle
  File "direct.distributed.AstronClientRepository", line 64, in handleDatagram
  File "direct.distributed.ClientRepositoryBase", line 438, in handleUpdateField
  File "direct.distributed.ClientRepositoryBase", line 446, in __doUpdate
  File "lib.coginvasion.battle.DistributedPieTurretManager", line 57, in turretPlaced
  File "lib.coginvasion.battle.DistributedPieTurret", line 65, in b_setGag
  File "direct.distributed.DistributedObject", line 359, in sendUpdate
AssertionError: Don't know how to pack object: None at line 861 of c:\users\brian\desktop\panda3d-master\direct\src\dcparser\dcPacker.cxx

**Comment by InvisbleMario** [comment]
Same thing has happened twice to me now. It seems if you have a turret left over from a previous battle and try to place it you crash. Maybe somehow remove the turret from your "inventory" after you win/die?

**Comment by xMakerx** [comment]
This bug has been patched in v1.0.3.
