### ISSUE TITLE
Crash caused by gag shop?

### ISSUE THREAD

**Issue by InvisbleMario** [InvisbleMario/CIOIssueTracker#4]
I cancelled the gag shop gui and got this

Log:
Traceback (most recent call last):
  File "__main__", line 12, in <module>
  File "lib.coginvasion.base.CIStartGlobal", line 11, in <module>
  File "lib.coginvasion.base.CIStart", line 142, in <module>
  File "direct.showbase.ShowBaseWide", line 2982, in run
  File "direct.task.Task", line 508, in run
  File "direct.task.Task", line 465, in step
  File "direct.showbase.EventManager", line 52, in eventLoopTask
  File "direct.showbase.EventManager", line 46, in doEvents
  File "direct.showbase.EventManager", line 103, in processEvent
  File "direct.showbase.Messenger", line 326, in send
  File "direct.showbase.Messenger", line 411, in __dispatch
  File "direct.gui.DirectButton", line 103, in commandFunc
  File "lib.coginvasion.shop.GagShop", line 104, in cancelPurchase
ValueError: too many values to unpack

**Comment by xMakerx** [comment]
This issue has been corrected and will have its correction on the live server next update.
