### ISSUE TITLE
Chat causes crash in race game?

### ISSUE THREAD

**Issue by InvisbleMario** [InvisbleMario/CIOIssueTracker#9]
Traceback (most recent call last):
  File "direct.showbase.EventManager", line 52, in eventLoopTask
  File "direct.showbase.EventManager", line 46, in doEvents
  File "direct.showbase.EventManager", line 103, in processEvent
  File "direct.showbase.Messenger", line 326, in send
  File "direct.showbase.Messenger", line 411, in __dispatch
  File "direct.gui.DirectButton", line 103, in commandFunc
  File "lib.coginvasion.gui.ChatInput", line 93, in openChatInput
  File "direct.fsm.ClassicFSM", line 286, in request
  File "direct.fsm.ClassicFSM", line 232, in __transition
  File "direct.fsm.ClassicFSM", line 217, in __enter
  File "direct.fsm.State", line 202, in enter
  File "lib.coginvasion.gui.ChatInput", line 105, in enterInput
  File "direct.fsm.ClassicFSM", line 286, in request
  File "direct.fsm.ClassicFSM", line 232, in __transition
  File "direct.fsm.ClassicFSM", line 217, in __enter
  File "direct.fsm.State", line 202, in enter
TypeError: enterInput() takes exactly 2 arguments (1 given)
Traceback (most recent call last):
  File "__main__", line 12, in <module>
  File "lib.coginvasion.base.CIStartGlobal", line 11, in <module>
  File "lib.coginvasion.base.CIStart", line 142, in <module>
  File "direct.showbase.ShowBaseWide", line 2982, in run
  File "direct.task.Task", line 508, in run
  File "direct.task.Task", line 465, in step
  File "direct.showbase.EventManager", line 52, in eventLoopTask
  File "direct.showbase.EventManager", line 46, in doEvents
  File "direct.showbase.EventManager", line 103, in processEvent
  File "direct.showbase.Messenger", line 326, in send
  File "direct.showbase.Messenger", line 411, in __dispatch
  File "direct.gui.DirectButton", line 103, in commandFunc
  File "lib.coginvasion.gui.ChatInput", line 93, in openChatInput
  File "direct.fsm.ClassicFSM", line 286, in request
  File "direct.fsm.ClassicFSM", line 232, in __transition
  File "direct.fsm.ClassicFSM", line 217, in __enter
  File "direct.fsm.State", line 202, in enter
  File "lib.coginvasion.gui.ChatInput", line 105, in enterInput
  File "direct.fsm.ClassicFSM", line 286, in request
  File "direct.fsm.ClassicFSM", line 232, in __transition
  File "direct.fsm.ClassicFSM", line 217, in __enter
  File "direct.fsm.State", line 202, in enter
TypeError: enterInput() takes exactly 2 arguments (1 given)

**Comment by mgracer48** [comment]
obviously because you need to give 1 arguments not 1

**Comment by mgracer48** [comment]
this what u need to fix
File "lib.coginvasion.gui.ChatInput", line 105, in enterInput
